### ISSUE TITLE
I can't install ocr-weighted-levenshtein nor weighted-levenshtein

### ISSUE THREAD

**Issue by EloiDuchaussoy** [zas97/ocr_weighted_levenshtein#1]
This project is exactly what I need for my own project (brands detection on photos with tesseract OCR), but I can't seem to install them with pip.
Any ideas on how to fix this or circumvent pip entierely?

EDIT: I managed to install ocr-weighted_levenhstein by cloning the git and running a local pip install, but now when I call .get_distances_params(), I have an error saying that there is no attibute with such a name

**Comment by zas97** [comment]
Will try to solve it, meanwhile you can use the [iso](https://github.com/zas97/ocr_weighted_levenshtein/blob/main/distances.json) with the weighted levenshtein library

**Comment by zas97** [comment]
I updated the readme, installing ocr-weighted-levenshtein is no longer necessary since I don't have time to maintain it. From now on you can download a json and use it for the weights following the instructions in the readme
